docs: Form for bug issue creation
kyma-project/lifecycle-manager pull request #1042
Opened 2023-11-14 17:29 UTC by janmedrek

**Description**

Changes proposed in this pull request:

- Add a GitHub Form for the bug issue creation

You can check the looks [here](https://github.com/janmedrek/lifecycle-manager/blob/bug-template/.github/ISSUE_TEMPLATE/bug-report.yml). Formatting is a bit off though.

2023-11-15 14:19 UTC, mmitoraj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: Provide your list here.
```suggestion
      placeholder: Provide your list of steps here.
```

2023-11-15 14:19 UTC, mmitoraj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        ### To help us identify and resolve the issue efficiently please consider attaching the following:
```suggestion
        ### To help us identify and resolve the issue efficiently, please consider attaching the following:
```

2023-11-15 14:19 UTC, mmitoraj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      placeholder: Put your attachments in here.
```suggestion
      placeholder: Add your attachments here.
```

2023-11-15 14:19 UTC, mmitoraj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: More information on the environment where the bug was found.
```suggestion
      description: More information on the environment where you found the bug.
```
The less passive and more active voice the better :)

2023-11-15 14:19 UTC, mmitoraj commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        ### Thank you for your report. Before you submit the issue please:
```suggestion
        ### Thank you for your report. Before you submit the issue, please:
```

2023-11-16 08:50 UTC, lindnerby requested changes

2023-11-16 08:50 UTC, lindnerby commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        - minikube
Not sure if Minikube is a widely used env option here. We should definitely add k3d as an option here, same  in line 46 to add k3d/k3s version.

2023-11-16 08:50 UTC, lindnerby commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Minikube Version: x.y.z
Other versions of interest (if applicable) could be used Kyma CLI

2023-11-16 12:53 UTC, mmitoraj submitted a review, later dismissed

2023-11-16 15:10 UTC, lindnerby approved these changes

2023-11-17 07:14 UTC, mmitoraj approved these changes

2023-11-17 07:17 UTC, merged