fix: Return error when doing ssa for diff in declarative library
kyma-project/lifecycle-manager pull request #1495
Opened 2024-04-23 11:57 UTC by nesmabadr

**Description**

Changes proposed in this pull request:

- Return error when doing ssa for diff in declarative library

**Related issue(s)**
Resolves #1399

2024-04-26 05:25 UTC, Tomasz-Smelcerz-SAP commented on internal/declarative/v2/reconciler.go
>  			return r.removeFinalizers(ctx, obj, []string{r.Finalizer}, metrics.ManifestRemoveFinalizerWhenParseSpec)
I think here we're also ignoring the original error. It is clearly visible in the `removeFinalizers` function, in the line 256.

2024-04-26 05:35 UTC, Tomasz-Smelcerz-SAP commented on internal/declarative/v2/reconciler.go
> +	requeueReason metrics.ManifestRequeueReason, previousStatus shared.Status, err error,
Small suggestion: This parameter name: `err` is later shadowed by the variable defined in the line 647.
Shadowing may be confusing: one has to read the code very carefully to understand the scopes of the "original" vs "shadowed" variable.
I'd vote for renaming this parameter to "originalErr" or "externalErr" to better describe the purpose of this parameter and avoid shadowing.

2024-04-26 05:44 UTC, Tomasz-Smelcerz-SAP requested changes
Please see my comments

2024-04-26 08:27 UTC, nesmabadr commented on internal/declarative/v2/reconciler.go
> +	return r.ssaStatusIfDiffExist(ctx, obj, requeueReason, currentObjStatus, nil)
ah good point. I was confused by the deletion condition that's why I missed that error

2024-04-26 09:11 UTC, Tomasz-Smelcerz-SAP approved these changes

2024-04-26 18:39 UTC, Tomasz-Smelcerz-SAP approved these changes

2024-04-29 04:31 UTC, Tomasz-Smelcerz-SAP approved these changes

2024-04-29 04:33 UTC, merged