chore: Provide condition and metrics for Manifests stuck in Deleting due to DefaultCR Warning
kyma-project/lifecycle-manager pull request #1988
Opened 2024-10-25 10:43 UTC by ruanxin

**Description**

**Related issue(s)**
https://github.com/kyma-project/lifecycle-manager/issues/1830

2024-11-04 15:05 UTC, lindnerby requested changes

2024-11-04 15:11 UTC, ruanxin commented on api/v1beta2/manifest_types.go
> +		return "", ErrLabelNotFound
I think two error is not necessary, but with fmt.Errorf to provide extra text could be helpful in this case.

2024-11-04 15:24 UTC, ruanxin commented on internal/manifest/finalizer/handler.go
> +func RemoveCRFinalizer(ctx context.Context, kcp client.Client, manifest *v1beta2.Manifest) error {
done

2024-11-04 15:24 UTC, ruanxin commented on internal/manifest/skrresources/sync.go
> +package skrresources
done

2024-11-05 07:23 UTC, lindnerby approved these changes

2024-11-05 09:03 UTC, merged