Refactor load_test as dedicate kustomize build instead of component
kyma-project/lifecycle-manager pull request #232
Opened 2022-10-04 15:01 UTC by ruanxin

- add load-test-deploy make command

2022-10-04 15:05 UTC, jakobmoellersap requested changes
I think this needs an explanation of why it is there and how it can be used in the main kustomization.yaml

Other than that, if its not used for active development it might be wort not setting a makefile target for this. Your choice on this though.

Generally LGTM :)

2022-10-05 12:07 UTC, ruanxin commented on operator/config/load_test/kustomization.yaml
>  resources:
```suggestion
# The main purpose of this dedicate kustomization file is separate resources configuration for load test from default setup, enable the ability to configure additional components.
resources:
```

2022-10-05 12:11 UTC, ruanxin commented
> I think this needs an explanation of why it is there and how it can be used in the main kustomization.yaml
> 
> Other than that, if its not used for active development it might be wort not setting a makefile target for this. Your choice on this though.
> 
> Generally LGTM :)

Make sense, I removed the makefile command, and added a comment to explain the purpose of that kustomization file, feel free add suggestions to the changes if needed.

2022-10-05 13:01 UTC, jakobmoellersap approved these changes

2022-10-05 13:03 UTC, merged