remove Channel type
kyma-project/lifecycle-manager pull request #332
Opened 2022-12-06 23:55 UTC by ruanxin

2022-12-13 13:19 UTC, Tomasz-Smelcerz-SAP commented on api/v1alpha1/kyma_types.go
> +	Channel string `json:"channel"`
Validation as above

2022-12-13 13:19 UTC, Tomasz-Smelcerz-SAP commented on api/v1alpha1/kyma_types.go
> +	ActiveChannel string `json:"activeChannel,omitempty"`
I assume this should have the same validation as the "Channel" field.

2022-12-13 13:23 UTC, Tomasz-Smelcerz-SAP commented on api/v1alpha1/moduletemplate_types.go
> +	Channel string `json:"channel"`
Validation as above

2022-12-13 13:29 UTC, Tomasz-Smelcerz-SAP requested changes
I think we must set a min and max for channel length, to avoid single-letter channel names and more than 10k chars long names. The latter could be used for DOS attacks.

2022-12-13 13:34 UTC, Tomasz-Smelcerz-SAP reviewed
I think we must set a min and max for channel length, to avoid single-letter channel names and names with more than, say, 10k chars. The latter could be used for DOS attacks.

2022-12-15 21:21 UTC, adityabhatia approved these changes

2022-12-15 21:23 UTC, merged