Migration go v4
kyma-project/lifecycle-manager pull request #869
Opened 2023-09-21 13:42 UTC by jeremyharisch

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-09-29 13:26 UTC, nataliasitko submitted a review, later dismissed

2023-10-05 06:17 UTC, lindnerby requested changes
Migration changes look good, tested all related make targets and the changes align with the manual migration guide.
Just can you please extract the golangci-lint config move changeset to another PR (if you think these changes are really necessary)

2023-10-05 08:13 UTC, nataliasitko approved these changes

2023-10-05 08:14 UTC, lindnerby approved these changes

2023-10-05 08:27 UTC, merged